Rem THIS FILE IS PLACED HERE TO PREVENT POTENTIAL ATTACKERS FROM USING THE compile_settings_schema.bat TO GAIN
Rem ADMINISTRATOR ACCESS ON WINDOWS. DO NOT REMOVE THIS FILE OR EDIT IT.
Rem
Rem FOR MORE INFO, EMAIL FEKHESK@PM.ME OR MESSAGE HUSKY SOMEHOW IDK
